### PR TITLE
Raise error on out of bounds.

### PR DESCRIPTION
**Pull request by bradgignac**
This address issue #13.

### CODE REVIEW

**Comment by bradgignac** [comment]
I had a few minutes to knock this out, so I went ahead and submitted a pull request. Let me know if you have any questions or concerns.

**Comment by bradgignac** [comment]
@tomeara Mind taking a look at this?

**Comment by tomeara** [comment]
@bradgignac I checked out your pull request, and it looks great! Unfortunately, I am no longer with Intridea, so I do not have the permissions to merge your pull request. I would recommend someone at @intridea to merge though...

**Comment by bradgignac** [comment]
Closing this and re-opening in the new repository.

**Pull request closed without merging**
